const ERROR = 'ERROR'
const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS'
const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
const MODAL_OPEN_CLOSE = 'MODAL_OPEN_CLOSE'
const PAGE_DECREMENT = 'PAGE_DECREMENT'
const PAGE_INCREMENT = 'PAGE_INCREMENT'
const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'

export {
    ERROR, 
    FETCH_CHARACTERS_SUCCESS, 
    FETCH_LOCATIONS_SUCCESS,
    MODAL_OPEN_CLOSE,
    PAGE_DECREMENT,
    PAGE_INCREMENT,  
    SET_SEARCH_TEXT
}

